name: Dependencies

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual runs

jobs:
  update-deps:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
          
      - name: Check for outdated packages
        run: |
          pip list --outdated
          
      - name: Update requirements.txt
        run: |
          # Create a temporary requirements file with latest versions
                  pip install --upgrade yt-dlp
        pip freeze | grep -E "(yt-dlp)" > requirements_latest.txt
          
          echo "Current requirements:"
          cat requirements.txt
          echo ""
          echo "Latest available versions:"
          cat requirements_latest.txt
          
      - name: Create Pull Request if updates available
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "🤖 Automated dependency updates"
          body: |
            This PR was automatically created to update dependencies.
            
            ## Changes
            - Updated package versions
            - Security improvements
            
            ## Checklist
            - [ ] Tests pass
            - [ ] No breaking changes
            - [ ] Documentation updated
          branch: dependabot/update-dependencies
          delete-branch: true 